export const ENVIRONMENT = process.env.ENVIRONMENT || "NO_ENVIRONMENT_SPECIFIED";
export const AWS_REGION = process.env.AWS_REGION || "NO_AWS_REGION_SPECIFIED";
export const SLACK_VERIFICATION_TOKEN = process.env.SLACK_VERIFICATION_TOKEN || "NO_SLACK_VERIFICATION_TOKEN_SPECIFIED";
export const SEND_WEBHOOK_URL = process.env.SEND_WEBHOOK_URL || "NO_SEND_WEBHOOK_URL_SPECIFIED";
export const SLACK_OAUTH_TOKEN = process.env.SLACK_OAUTH_TOKEN || "NO_SLACK_OAUTH_TOKEN_SPECIFIED";

// Parking Garage specific
export const ALERT_CHANNEL_ID = process.env.ALERT_CHANNEL_ID || "NO_ALERT_CHANNEL_ID_SPECIFIED";
export const PARKING_CHANNEL_ID = process.env.PARKING_CHANNEL_ID || "NO_PARKING_CHANNEL_ID_SPECIFIED";
export const JACOB_SLACK_ID = process.env.JACOB_SLACK_ID || "NO_JACOB_SLACK_ID_SPECIFIED";
export const ANIRUDH_SLACK_ID = process.env.ANIRUDH_SLACK_ID || "NO_ANIRUDH_SLACK_ID_SPECIFIED";